import { mapDataPoint } from "./data";

import {
  pBaban,
  pBayazid,
  pBitlis,
  pBokhti,
  pDozhik,
  pHakkari,
  pJelali,
  pMilan,
  pSoran,
  pTasini,
} from "./paths/pFuerstentuemer";

const colorFuerstentuemer = "#e74322";

export const dFuerstentuemer: mapDataPoint[] = [
  {
    id: 0,
    color: colorFuerstentuemer,
    outline: 3,
    opacity: 1,
    outlineColor: "#c12020",
    title: "Baban",
    path: pBaban,
  },
  {
    id: 1,
    color: colorFuerstentuemer,
    outline: 3,
    opacity: 1,
    outlineColor: "#c12020",
    title: "Bayazid",
    path: pBayazid,
  },
  {
    id: 2,
    color: colorFuerstentuemer,
    opacity: 1,
    outline: 3,
    outlineColor: "#c12020",
    title: "Bitlis",
    path: pBitlis,
  },
  {
    id: 3,
    color: colorFuerstentuemer,
    opacity: 1,
    outline: 3,
    outlineColor: "#c12020",
    title: "Bokhti",
    path: pBokhti,
  },
  {
    id: 4,
    color: colorFuerstentuemer,
    opacity: 1,
    outline: 3,
    outlineColor: "#c12020",
    title: "Dozhik",
    path: pDozhik,
  },
  {
    id: 5,
    color: colorFuerstentuemer,
    opacity: 1,
    outline: 3,
    outlineColor: "#c12020",
    title: "Hakkari",
    path: pHakkari,
  },
  {
    id: 6,
    color: colorFuerstentuemer,
    opacity: 1,
    outline: 3,
    outlineColor: "#c12020",
    title: "Jelali",
    path: pJelali,
  },
  {
    id: 7,
    color: colorFuerstentuemer,
    opacity: 1,
    outline: 3,
    outlineColor: "#c12020",
    title: "Milan",
    path: pMilan,
  },
  {
    id: 8,
    color: colorFuerstentuemer,
    opacity: 1,
    outline: 3,
    outlineColor: "#c12020",
    title: "Soran",
    path: pSoran,
  },
  {
    id: 9,
    color: colorFuerstentuemer,
    opacity: 1,
    outline: 3,
    outlineColor: "#c12020",
    title: "Tasini",
    path: pTasini,
  },
];
